version: "3.9"

services:
  # BASE DE DATOS POSTGRES
  db:
    image: postgres:15
    container_name: registro_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - registro_network
    ports:
      - "5432:5432"

  # ADMINER (para DB development)
  adminer:
    image: adminer:latest
    container_name: registro_adminer
    restart: always
    depends_on:
      - db
    networks:
      - registro_network
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

  # BACKEND DJANGO
  backend:
    image: registro-backend:1.0.0
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: registro_backend
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: registro.settings
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SECRET_KEY: ${DJANGO_SECRET_KEY}
    volumes:
      - ./backend:/app
    networks:
      - registro_network
    ports:
      - "8000:8000"
    command: gunicorn registro.wsgi:application --bind 0.0.0.0:8000 --workers 3

  # FRONTEND ANGULAR + NGINX
  frontend:
    image: registro-frontend:1.0.0
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: registro_frontend
    depends_on:
      - backend
    networks:
      - registro_network
    ports:
      - "8082:80"

# REDES PERSONALIZADAS
networks:
  registro_network:
    driver: bridge

# VOLÚMENES PERSISTENTES
volumes:
  postgres_data:
