version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
      POSTGRES_USER: ${POSTGRES_USER:-appuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apppassword}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_net

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-appuser}:${POSTGRES_PASSWORD:-apppassword}@postgres:5432/${POSTGRES_DB:-appdb}
      - DJANGO_SETTINGS_MODULE=registro.settings
      - SECRET_KEY=${SECRET_KEY:-dev-secret}
      - DEBUG=${DEBUG:-1}
    volumes:
      - ./backend/:/app
    ports:
      - "8000:8000"
    networks:
      - app_net

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - app_net

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - app_net

volumes:
  pgdata:

networks:
  app_net:
    driver: bridge
