apiVersion: apps/v1
kind: Deployment
metadata:
  name: registro-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: registro-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: registro-backend
    spec:
      containers:
        - name: backend
          image: registro-backend:2.0.0  
          imagePullPolicy: IfNotPresent                 
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: registro-secrets
