apiVersion: v1
kind: Namespace
metadata:
  name: app-registro
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app-registro
data:
  DJANGO_SETTINGS_MODULE: "registro.settings"
  DEBUG: "False"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app-registro
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ
  SECRET_KEY: ZGV2X3NlY3
