apiVersion: v1
kind: Service
metadata:
  name: registro-backend-service
  labels:
    app: registro-backend
spec:
  type: LoadBalancer
  selector:
    app: registro-backend
  ports:
    - name: http
      port: 8000        # Puerto interno del servicio (el que usarán otros pods)
      targetPort: 8000  # Puerto en el contenedor backend (del Deployment)
