# Generated by Django 5.2.7 on 2025-10-24 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15, verbose_name='Denominacion del tipo de documento')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado actual del tipo de documento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ci', models.CharField(max_length=10, verbose_name='Numero de carnet')),
                ('nombre_completo', models.CharField(max_length=50, verbose_name='Nombre completo del usuario')),
                ('correo_electronico', models.CharField(max_length=50, verbose_name='Correo electronico')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado actual del usuario')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_documento', to='usuario.documento')),
            ],
        ),
    ]
